# Generated by Django 5.0.6 on 2025-05-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
    ]
