# Generated by Django 5.0.6 on 2025-05-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answer_time_spent_question_answer_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='time_spent',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.RemoveField(
            model_name='round',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='round',
            name='start_time',
        ),
    ]
