# Generated by Django 5.0.6 on 2025-05-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_userround'),
    ]

    operations = [
        migrations.AddField(
            model_name='userround',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
