# Generated by Django 5.0.6 on 2025-05-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_userround_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Email tasdiqlanganmi?'),
        ),
    ]
