# Generated by Django 5.0.6 on 2025-06-01 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user_round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.userround'),
            preserve_default=False,
        ),
    ]
