# Generated by Django 5.0.6 on 2025-06-01 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_answer_user_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.userround'),
        ),
    ]
