# Generated by Django 5.0.6 on 2025-06-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_answer_user_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
    ]
