# Generated by Django 5.0.6 on 2025-06-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_question_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userround',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
