# Generated by Django 5.0.6 on 2025-06-01 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_userround_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userround',
            name='ended_at',
        ),
    ]
