# Generated by Django 5.0.6 on 2025-06-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_remove_userround_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userround',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
