# Generated by Django 5.0.6 on 2025-06-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_userround_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
