# Generated by Django 5.0.6 on 2025-06-02 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_question_option_4_question_option_5'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userround',
            unique_together={('user', 'round')},
        ),
    ]
