# Generated by Django 5.0.6 on 2025-06-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_alter_userround_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userround',
            unique_together=set(),
        ),
    ]
